### ISSUE TITLE
FR 11 - Application is able to export ESM queue to JSON format.

### ISSUE THREAD

**Issue by NBerkel** [NBerkel/ESM-Creator#11]

**Comment by NBerkel** [comment]
Added ESM expiry time functionality https://github.com/NBerkel/ESM-Creator/commit/296cab894fc73018e9fd0c37977a4206c7b2ce4d

**Comment by mvahida** [comment]
Perfect! just the format should change to how is implemented in the data base. I think I should do this part since I did the database part. I assign it to myself.
